### ISSUE TITLE
Html errors

### ISSUE THREAD

**Issue by MarkoZabcic** [lexrupy/rails-footnotes-linux#1]
special characters aren't escaped %, <,>

**Comment by lexrupy** [comment]
Please test again, I merged from josevalim branch, this issue may be solved there.
you will need to wait github regenerate the gem

**Comment by MarkoZabcic** [comment]
I've reinstalled it as plugin and & is properly escaped to &amp; but there is still issue with <>.
Example:
<td>action_controller.rescue.request</td><td>#ActionController::Request:0x7f4ca3d738f8</td>

Where <> aren't escaped to &lt; &gt;

Thanks, Marko
